((:COHORT PRIORITY :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 1
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 19 :PLAN-ID |plan15394| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 6 :FIRST-UNSAT
   (|op15392| (ISPEG $15390)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1825 :MP-PRUNED 0))
 (:COHORT PRIORITY :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 19 :PLAN-ID |plan15385| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 6 :FIRST-UNSAT
   (|op15383| (ISPEG $15381)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1830 :MP-PRUNED 0))
 (:COHORT PRIORITY :SOURCE-RANK 3 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 19 :PLAN-ID |plan15380| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 6 :FIRST-UNSAT
   (|op15378| (ISPEG $15376)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1837 :MP-PRUNED 0))
 (:COHORT PRIORITY :SOURCE-RANK 4 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 20 :PLAN-ID |plan15365| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 7 :FIRST-UNSAT
   (|op15362| (ISPEG $15360)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1820 :MP-PRUNED 0))
 (:COHORT PRIORITY :SOURCE-RANK 5 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 21 :PLAN-ID |plan15358| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 6 :FIRST-UNSAT
   (|op15356| (ISPEG $15354)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1818 :MP-PRUNED 0)))
