; SBCL-only forward declarations for historical source-load order.
; These reduce undefined-function style warnings during source loading
; without changing planner behavior.

(declaim
 (ftype function
        ith
        create-var
        remove-all-var-pairs
        var-p
        all_preconds_hold-p
        get-opids-from-plan
        this_opid_ok-p
        get-preconditions-of-opid
        preconds_hold-p
        hold-p
        find_establishers
        one-of-establishers-ok-p
        clobberer-exists-p
        all-poss-between
        get-effects-of-opid
        poss-codesignates
        declobber-all
        determine-user-and-precond
        find-exist-ests
        find-new-ests
        invalid-p
        precond-to-index
        determine-first-user-and-precond
        determine-random-user-and-precond
        unsat-user-precond-pairs
        tw-heuristic-function-1
        user-heuristic
        num-of-unsat-goals
        find-new-plan
        get-operator-opid
        select-ops
        add-cost-to-plan
        add-operator-to-plan
        add-order-to-plan
        apply-mapping-to-plan
        get-operator-cost
        make-copy-of-plan
        find-list-of-op-instances
        apply-mapping-to-op-instance
        create-new-op-instance
        get-ith-op-effect
        get-operator-effects
        get-operator-primary-effects
        find-nec-exist-ests
        find-pos-exist-ests
        all-poss-before
        find_pos_est_pairs
        make-pos-intermediates
        make-est
        add-co-to-plan
        find_est_effect_pairs_for_pos-est
        find-all-poss-codes-effects
        nece-before-p
        cur
        get-conflict-n
        get-conflict-pro
        get-conflict-u
        poss-before-p
        declobber
        get-inter-estid
        get-inter-plan
        apply-constraints-to-plan
        create-alternative-constraints
        create-cart-products
        create-conflict-list-for-tuple
        create-set-of-constraints
        get-conflict-p
        get-conflict-q
        separation-list
        apply-this-constraint-to-plan
        add-nc-to-plan
        type-of-constraint
        create-conflict-list-for-opid
        create-conflict-list-for-precond
        find-n-q-pairs
        n-q-pairs-for-this-candidate
        transitive-test-before-p
        remove-constant-nonco
        mark-invalid-plan
        nece-codesignates-p
        clean-up-nc
        get-condition-in-cr
        get-producer-list-in-cr
        get-user-in-cr
        remv-redun-orders
        add-para-ncodes
        all-nece-before
        nece-est-p
        remove-redundant-establishers
        np-codesignates-p
        nots-do-not-match
        strip-negate
        substitute-this-by-that
        replace-by-op-name
        sort-orders
        write-one-plan-to-file
        all-successors
        initialize-abs-branching-counts
        initialize-abs-ref-counts
        initialize-success-ref-counts
        compute-total-cost
        first-of-open
        get-abs-branching-count
        get-next-open-node
        get-state
        goal-p
        initialize-closed
        initialize-open
        insert-node
        length-of-open
        list-empty-p
        make-node
        remove-first-node
        reset-abs-branching-counts
        stack-get-next-open-node
        stack-initialize-open
        stack-insert-node
        stack-length-of-open
        stack-remove-first-node
        successors&costs
        which-heuristic-function
        get-priority
        find-initial-k-val
        ab-mtc
        ab-successors
        ab-all_preconds_hold-p
        ab-this_opid_ok-p
        find-crit
        ab-determine-u-and-p
        add-a-level
        increment-abs-branching-count
        update-abs-ref-counts
        update-abs-succ-counts
        ab-determine-first-u-and-p
        ab-determine-random-u-and-p
        adjust-pre-list
        ab-unsat-up-pairs
        find-k-cr
        get-est-tuples
        get-level-k-oplist
        get-level-k-pre
        get-est-this-op
        get-this-level-k-type
        create-tuples
        find-this-a-pre
        equal-pre
        violates-mp-weak
        exists-mp-violation-p
        this-one-violated
        asserts-negative
        asserts-positive
        adjust-pre-list-others
        find-crit1
        substitute-pre
        find-pre-head
        sub-pre-tail
        contains-constants-p
        remove-a-constant
        find-right-constant
        replace-i
        sublist
        update-op-count
        total-ops
        left-wedge-function
        add-cr-to-successors
        find-one-mr-conflict
        mr-declob
        mr-determine-user-and-precond
        mr-determine-first-user-and-precond
        produced-already-p
        create-conflicts-one-step
        find-step-effect-pairs
        mr-n_q-pairs-for-this-candidate
        mr-n-q-pairs-for-this-candidate
        make-initial-plan))
