; Extra special-variable declarations for the SBCL working port.
; These preserve the historical source style while reducing noisy
; undefined-special warnings during source loading on modern CLs.

(defvar *solution* nil)
(defvar *solution-limit* 0)
(defvar *continue-p* nil)
(defvar *control-strategy* 'bfs)
(defvar *abstract-goal-mode* nil)
(defvar *heuristic-mode* nil)
(defvar *subgoal-determine-mode* nil)
(defvar *use-primary-effect-p* nil)
(defvar *cpu-sec-limit* 0)
(defvar *drp-debug-mode* nil)
(defvar *drp-stack* nil)
(defvar *existing-only* nil)
(defvar *output-stream* nil)
(defvar *open* nil)
(defvar *closed* nil)
(defvar *internal-start-time* 0)
(defvar *curr-level* 0)
(defvar *abs-backtracking-flag* nil)
(defvar *max-succ-count* 0)
(defvar *critical-list* nil)
(defvar *critical-list-1* nil)
(defvar *critical-list-2* nil)
(defvar *critical-loaded* nil)
(defvar *abs-branching-counts* nil)
(defvar *abs-ref-counts* nil)
(defvar *abs-success-counts* nil)
(defvar *new-refinement-p* nil)
(defvar *success* nil)
(defvar *sol* nil)
(defvar *err-conflict* nil)
(defvar *error-plan* nil)
(defvar *confl-count* 0)
(defvar *mr-debug* nil)
(defvar *tc-mode* nil)
(defvar *ps* nil)
(defvar *cs* nil)
(defvar *ismb* nil)
(defvar *imbs* nil)
(defvar *k-list-1* nil)
(defvar *k-list-2* nil)

; Historical files sometimes rely on implicit specials for scratch values.
(defvar a nil)
(defvar b nil)
(defvar c nil)
(defvar d nil)
(defvar goals nil)
(defvar goalm nil)
(defvar goalb nil)
(defvar p nil)
(defvar s nil)
(defvar up nil)
(defvar producer-id-list nil)
(defvar result nil)
