((:COHORT CLOSURE :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 7 :SEARCH-COST 7 :HEURISTIC-COMPONENT 0 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 15 :PLAN-ID |plan113856| :PLAN-COST
   7 :PLAN-KVAL 2 :PLAN-LENGTH 9 :UNSAT-COUNT 2 :FIRST-UNSAT
   (|op113854| (ISPEG $113852)) :NEXT-USER-PRECOND
   (|op113854| (ISPEG $113852)))
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   10001 :NUM-GENERATED 13680 :MP-PRUNED 10666))
 (:COHORT CLOSURE :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 10 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 23 :PLAN-ID |plan120816| :PLAN-COST
   10 :PLAN-KVAL 1 :PLAN-LENGTH 12 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op120813| (ISPEG $120811)) :NEXT-USER-PRECOND
   (|op120813| (ISPEG $120811)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 271 :NUM-GENERATED
   270 :MP-PRUNED 315))
 (:COHORT CLOSURE :SOURCE-RANK 3 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 10 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 23 :PLAN-ID |plan120781| :PLAN-COST
   10 :PLAN-KVAL 1 :PLAN-LENGTH 12 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op120779| (ISPEG $120777)) :NEXT-USER-PRECOND
   (|op120779| (ISPEG $120777)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 271 :NUM-GENERATED
   270 :MP-PRUNED 90))
 (:COHORT CLOSURE :SOURCE-RANK 4 :SOURCE
  (:PRIORITY 6 :SEARCH-COST 11 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 25 :PLAN-ID |plan32092| :PLAN-COST
   11 :PLAN-KVAL 1 :PLAN-LENGTH 13 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op32090| (ISPEG $32088)) :NEXT-USER-PRECOND (|op32090| (ISPEG $32088)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 268 :NUM-GENERATED
   267 :MP-PRUNED 89))
 (:COHORT CLOSURE :SOURCE-RANK 5 :SOURCE
  (:PRIORITY 6 :SEARCH-COST 11 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 25 :PLAN-ID |plan32058| :PLAN-COST
   11 :PLAN-KVAL 1 :PLAN-LENGTH 13 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op32056| (ISPEG $32054)) :NEXT-USER-PRECOND (|op32056| (ISPEG $32054)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 268 :NUM-GENERATED
   267 :MP-PRUNED 312)))
