((:COHORT PRIORITY :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 4 :SEARCH-COST 12 :HEURISTIC-COMPONENT -8 :BASE-GOAL-HEURISTIC 1
   :LEFT-WEDGE-ADJUSTMENT -9 :SOLUTION-DEPTH 38 :PLAN-ID |plan127693|
   :PLAN-COST 12 :PLAN-KVAL 0 :PLAN-LENGTH 14 :UNSAT-COUNT 7 :FIRST-UNSAT
   (|op115343| (NOT ONM PEG1)) :NEXT-USER-PRECOND (|op115343| (NOT ONM PEG1)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 263 :NUM-GENERATED
   262 :MP-PRUNED 87))
 (:COHORT PRIORITY :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 4 :SEARCH-COST 12 :HEURISTIC-COMPONENT -8 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 38 :PLAN-ID |plan127692| :PLAN-COST
   12 :PLAN-KVAL 0 :PLAN-LENGTH 14 :UNSAT-COUNT 7 :FIRST-UNSAT
   (|op115343| (NOT ONM PEG1)) :NEXT-USER-PRECOND (|op115343| (NOT ONM PEG1)))
  :REPLAY
  (:RESULT NIL :SOLUTION CPU-TIME-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   2857 :NUM-GENERATED 2899 :MP-PRUNED 1611))
 (:COHORT PRIORITY :SOURCE-RANK 3 :SOURCE
  (:PRIORITY 4 :SEARCH-COST 12 :HEURISTIC-COMPONENT -8 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 35 :PLAN-ID |plan117044| :PLAN-COST
   12 :PLAN-KVAL 0 :PLAN-LENGTH 14 :UNSAT-COUNT 14 :FIRST-UNSAT
   (|op117037| (ISPEG $117036)) :NEXT-USER-PRECOND
   (|op117037| (ISPEG $117036)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 3 :NUM-GENERATED 2
   :MP-PRUNED 6))
 (:COHORT PRIORITY :SOURCE-RANK 4 :SOURCE
  (:PRIORITY 4 :SEARCH-COST 12 :HEURISTIC-COMPONENT -8 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 35 :PLAN-ID |plan117042| :PLAN-COST
   12 :PLAN-KVAL 0 :PLAN-LENGTH 14 :UNSAT-COUNT 11 :FIRST-UNSAT
   (|op117037| (ISPEG $117036)) :NEXT-USER-PRECOND
   (|op117037| (ISPEG $117036)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 3 :NUM-GENERATED 2
   :MP-PRUNED 6))
 (:COHORT PRIORITY :SOURCE-RANK 5 :SOURCE
  (:PRIORITY 4 :SEARCH-COST 12 :HEURISTIC-COMPONENT -8 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 34 :PLAN-ID |plan117031| :PLAN-COST
   12 :PLAN-KVAL 0 :PLAN-LENGTH 14 :UNSAT-COUNT 12 :FIRST-UNSAT
   (|op117027| (ISPEG $117025)) :NEXT-USER-PRECOND
   (|op117027| (ISPEG $117025)))
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   10001 :NUM-GENERATED 10464 :MP-PRUNED 8601)))
