((:COHORT CLOSURE :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 20 :PLAN-ID |plan15351| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 5 :FIRST-UNSAT
   (|op15348| (ISPEG $15346)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   3001 :NUM-GENERATED 5555 :MP-PRUNED 0))
 (:COHORT CLOSURE :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 20 :PLAN-ID |plan15222| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 5 :FIRST-UNSAT
   (|op15220| (ISPEG $15218)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   3001 :NUM-GENERATED 5512 :MP-PRUNED 0))
 (:COHORT CLOSURE :SOURCE-RANK 3 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 19 :PLAN-ID |plan15215| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 5 :FIRST-UNSAT
   (|op15212| (ISPEG $15210)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   3001 :NUM-GENERATED 5508 :MP-PRUNED 0)))
