((:COHORT PRIORITY :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 1
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 19 :PLAN-ID |plan15394| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 6 :FIRST-UNSAT
   (|op15392| (ISPEG $15390)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   3001 :NUM-GENERATED 5418 :MP-PRUNED 0))
 (:COHORT PRIORITY :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 19 :PLAN-ID |plan15385| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 6 :FIRST-UNSAT
   (|op15383| (ISPEG $15381)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   3001 :NUM-GENERATED 5468 :MP-PRUNED 0))
 (:COHORT PRIORITY :SOURCE-RANK 3 :SOURCE
  (:PRIORITY 10 :SEARCH-COST 9 :HEURISTIC-COMPONENT 1 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 19 :PLAN-ID |plan15380| :PLAN-COST
   9 :PLAN-KVAL 0 :PLAN-LENGTH 11 :UNSAT-COUNT 6 :FIRST-UNSAT
   (|op15378| (ISPEG $15376)) :NEXT-USER-PRECOND NIL)
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   3001 :NUM-GENERATED 5489 :MP-PRUNED 0)))
