((:COHORT PRIORITY :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 14 :HEURISTIC-COMPONENT -9 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT -9 :SOLUTION-DEPTH 42 :PLAN-ID |plan52005| :PLAN-COST
   14 :PLAN-KVAL 0 :PLAN-LENGTH 16 :UNSAT-COUNT 14 :FIRST-UNSAT
   (|op52003| (ISPEG $52001)) :NEXT-USER-PRECOND (|op52003| (ISPEG $52001)))
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1075 :MP-PRUNED 983))
 (:COHORT PRIORITY :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 14 :HEURISTIC-COMPONENT -9 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 41 :PLAN-ID |plan52000| :PLAN-COST
   14 :PLAN-KVAL 0 :PLAN-LENGTH 16 :UNSAT-COUNT 22 :FIRST-UNSAT
   (|op51997| (ISPEG $51996)) :NEXT-USER-PRECOND (|op51997| (ISPEG $51996)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 3 :NUM-GENERATED 2
   :MP-PRUNED 6))
 (:COHORT PRIORITY :SOURCE-RANK 3 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 14 :HEURISTIC-COMPONENT -9 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 38 :PLAN-ID |plan51980| :PLAN-COST
   14 :PLAN-KVAL 0 :PLAN-LENGTH 16 :UNSAT-COUNT 12 :FIRST-UNSAT
   (|op51977| (ISPEG $51975)) :NEXT-USER-PRECOND (|op51977| (ISPEG $51975)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 259 :NUM-GENERATED
   258 :MP-PRUNED 301))
 (:COHORT PRIORITY :SOURCE-RANK 4 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 14 :HEURISTIC-COMPONENT -9 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 38 :PLAN-ID |plan51961| :PLAN-COST
   14 :PLAN-KVAL 0 :PLAN-LENGTH 16 :UNSAT-COUNT 19 :FIRST-UNSAT
   (|op51958| (ISPEG $51956)) :NEXT-USER-PRECOND (|op51958| (ISPEG $51956)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 259 :NUM-GENERATED
   258 :MP-PRUNED 301))
 (:COHORT PRIORITY :SOURCE-RANK 5 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 14 :HEURISTIC-COMPONENT -9 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 39 :PLAN-ID |plan51950| :PLAN-COST
   14 :PLAN-KVAL 0 :PLAN-LENGTH 16 :UNSAT-COUNT 21 :FIRST-UNSAT
   (|op51948| (ISPEG $51946)) :NEXT-USER-PRECOND (|op51948| (ISPEG $51946)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 259 :NUM-GENERATED
   258 :MP-PRUNED 301)))
