((:COHORT CLOSURE :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 6 :SEARCH-COST 6 :HEURISTIC-COMPONENT 0 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 13 :PLAN-ID |plan33626| :PLAN-COST
   6 :PLAN-KVAL 2 :PLAN-LENGTH 8 :UNSAT-COUNT 2 :FIRST-UNSAT
   (|op33624| (ISPEG $33622)) :NEXT-USER-PRECOND (|op33624| (ISPEG $33622)))
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1386 :MP-PRUNED 968))
 (:COHORT CLOSURE :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 10 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 24 :PLAN-ID |plan10615| :PLAN-COST
   10 :PLAN-KVAL 1 :PLAN-LENGTH 12 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op10613| (ISPEG $10611)) :NEXT-USER-PRECOND (|op10613| (ISPEG $10611)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 271 :NUM-GENERATED
   270 :MP-PRUNED 90))
 (:COHORT CLOSURE :SOURCE-RANK 3 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 10 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 23 :PLAN-ID |plan8037| :PLAN-COST
   10 :PLAN-KVAL 1 :PLAN-LENGTH 12 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op8035| (ISPEG $8033)) :NEXT-USER-PRECOND (|op8035| (ISPEG $8033)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 271 :NUM-GENERATED
   270 :MP-PRUNED 90))
 (:COHORT CLOSURE :SOURCE-RANK 4 :SOURCE
  (:PRIORITY 6 :SEARCH-COST 11 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 26 :PLAN-ID |plan60183| :PLAN-COST
   11 :PLAN-KVAL 1 :PLAN-LENGTH 13 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op60181| (ISPEG $60179)) :NEXT-USER-PRECOND (|op60181| (ISPEG $60179)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 268 :NUM-GENERATED
   267 :MP-PRUNED 89))
 (:COHORT CLOSURE :SOURCE-RANK 5 :SOURCE
  (:PRIORITY 6 :SEARCH-COST 11 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 25 :PLAN-ID |plan32092| :PLAN-COST
   11 :PLAN-KVAL 1 :PLAN-LENGTH 13 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op32090| (ISPEG $32088)) :NEXT-USER-PRECOND (|op32090| (ISPEG $32088)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 268 :NUM-GENERATED
   267 :MP-PRUNED 89)))
