;;; -*- Syntax: Common-lisp; Package: USER -*-
;;; Copyright 1987 by Henry A. Kautz
;;; No warranty as to the correctness or usefulness of this software
;;; is given or implied.
;;;
;;; The author may be contacted at the following addresses:
;;; :uucp:	allegra!kautz		
;;; :arpa: or :csnet:	kautz@research.att.com
;;; :old style csnet: 	kautz%allegra@btl.csnet
;;; :mail:	AT&T Bell Laboratories	
;;;		Room 2C-407
;;;		600 Mountain Ave.	
;;;		Murray Hill, N.J. 07974	


(defparameter *stop-words* '(times oclock some any file 
			       graph graphs and the a time between))

(defparameter *stop-chars* '(#\, #\. #\\ #\/ #\? #\' #\" #\: #\; #\! #\( #\)))

(defun remove-stop-words (s)
  "remove stop words from sentence s, preserving order"
  (remove-if #'(lambda (w) (member w *stop-words*)) s))


;;; Note: the following is inefficient becauses it uses subseq, which copies
;;; its argument.
(defun read-list-from-string (str)
  "returns a list generated by reading all of string str"
  (multiple-value-bind (e end) (read-from-string str nil '***END-OF-STRING***)
    (if (eq e '***END-OF-STRING***)
      nil
      (nconc (list e) (read-list-from-string (subseq str end)))))
  )


(defun string-to-sentence (str)
  "convert string str into sentence in list form"
  (read-list-from-string (remove-if #'(lambda (c) (member c *stop-chars*)) str))
  )


(defun ee (str)
   "execute-english : parse english string, print its translation, and
 execute it"
   (let (com)
      (setq com (parse-sentence (string-to-sentence str)))
      (format t "~t Translation: ~a ~t" com)
      (eval com)))


(defvar *et-robust* nil)
(defvar *et-translate* t)
(defvar *et-echo* nil)

(defun execute-english-file (filename)
   (let ((*et-robust* nil) (*et-echo* t))
      (with-open-file (*standard-input* filename)
	 (english-toplevel)
	 )))

(defun english-toplevel ()
   (let (trimmed str com)
      (do () ()
	 (format t "~t Input: ")
	 (setq str (read-line nil nil "exit"))
	 (if *et-echo* (format t "~a ~t" str))
	 (setq trimmed (string-left-trim " " str))
	 (unless (or (= 0 (length trimmed))
		    (eql #\; (char trimmed 0)))
	    (setq com (parse-sentence (string-to-sentence str)))
	    (if (and (eq (car com) 'error) *et-robust*)
	       (format t "Huh?~t")
	       (else
		  (if *et-translate*
		     (format t "~t Translation: ~a ~t" com))
		  (if (eq (car com) 'exit) (return-from english-toplevel))
		  (format t "~%~{  ~A~%~}"
		     (multiple-value-list (eval com)))
		  ))
	    )
	 )))

(defmacro ml (&rest body) 
   "abbreviation for match-list"
   `(match-list ,@body))

(defmacro mss (&rest pat)
   "match a subsequence of s"
   `(match-list '(* ,@pat *) s))


(defvar *synonyms* '(
		       (cooks . makes)
		       (hypothesis . hypotheses)
		       (hypo . hypotheses)
		       (starts . starting)
		       (ends . ending)
		       ))

(defun replace-synonyms (s)
   "like s but with *synonyms* replaced"
   (mapcar #'(lambda (w) (or (cdr (assoc w *synonyms*)) w)) s))

(defvar *verbs* '(hunts robs cashes goes gets
		    copies deletes renames copy delete cp rm mv move rename
		    cooks makes boils
		    ))

(defun parse-english (str)
   (parse-sentence (string-to-sentence str)))

(defun parse-sentence (s)
   (let (
	   ;; dynamic variables for matching
	   b- b+ e- e+ filename var val graph graph1
	   graph2 graph3 agent
	   file1 file2
	   ;; regular lexical variables
	   detail
	   etype-and-descr
	   no-start-time no-end-time
	   time-roles agent-roles  )

      (declare (special b- b+ e- e+ filename var val detail graph
		  graph1 graph2 graph3 agent
		  file1 file2
		  *test-dir*
		  ))

      (setq s (remove-stop-words s))
      (setq s (replace-synonyms s))
      ;; determine command type
      (cond

	 ;; utility commands

	 ((eql s nil)
	    nil)
	 ((ml '((+ bye quit exit) ) s)
	    '(exit))
	 ((ml '((+ clear erase) *) s)
	    '(clear-all-mappings))
	 ((ml '((+ initialize init) *) s)
	    '(init-hypoths))
	 ((ml '(load  (? filename) ) s)
	    `(load (merge-pathnames 
		      ,(string-downcase
			  (string filename))
		      *test-dir*)))
	 ((ml '((+ no dont) trace *) s)
	    '(setq *noisy* nil))
	 ((ml '(trace *) s)
	    '(setq *noisy* t))
	 ((ml '(set (? var) (- to) (? val)) s)
	    `(setq ,var ',val))
	 ((ml '(* (+? var i n s incremental non-dichronic sticky)
		  (+ update updates))
	     s)
	    `(setq *update-type* ',var))

	 ;; display commands

	 ((ml '(show *) s)
	    (setq detail (ml '(* detail *) s))
	    (cond
	       ((ml '(show (+ all hypotheses) *) s)
		  `(display-hypoths ,detail))
	       ((ml '(show (- graph) (!? graph graph all hypo
					last explanation result
					hypotheses in detail) *) s)
		  `(draw-graph ,detail ',graph))
	       (t 
		  `(draw-graph ,detail))))

	 ;; matching commands

	 ((ml '(* match (? graph1) (- and) (? graph2) *) s)
	    (or 
	       (ml '(* (+ let giving into) (? graph3) *) s)
	       (setq graph3 (intern 
			       (concatenate 'string 
				  (string graph1) "+" (string
							 graph2))))
	       )
	    `(match-graphs ',graph1 ',graph2 ',graph3))
		  
	 ;; update and explain commands
	    
	 (t
	    ;; Event Descriptions

	    ;; determine event type and event specific roles
	    
	    (setq etype-and-descr
	       (cond

		  ;; hunt/rob world
		  
		  ((mss goes * woods)
		     `(go-to-woods))
		  
		  ((mss goes * bank)
		     `(go-to-bank))
		  
		  ((mss gets gun )
		     `(get-gun))

		  ((mss cashes )
		     `(cash-check))

		  ((mss robs )
		     `(robs-bank))

		  ;; file system world

		  ((mss (+ copies copy cp)  (? file1) (- to) (? file2))
		     `(copy (old ,file1) (new ,file2)))

		  ((mss (+ deletes delete rm)  (? file1))
		     `(delete (file ,file1)))

		  ((mss (+ mv move )  (? file1) (- to) (? file2))
		     `(move (old ,file1) (new ,file2)))
		  
		  ((mss edit  (? file1))
		     `(edit (file ,file1)))

		  ;; cooking world

		  ((mss (+ prepares makes) meal)
		     '(prepare-meal))
		  
		  ((mss makes pasta dish)
		     '(make-pasta-dish))

		  ((mss makes spaghetti marinara)
		     '(make-spaghetti-marinara))

		  ((mss makes fettucini alfredo)
		     '(make-fettucini-alfredo))

		  ((mss makes meat dish)
		     '(make-meat-dish))

		  ((mss makes chicken marinara)
		     '(make-chicken-marinara))

		  ((mss makes sauce)
		     '(make-sauce))

		  ((mss makes marinara)
		     '(make-marinara))

		  ((mss makes alfredo)
		     '(make-alfredo))

		  ((mss makes (+ noodles pasta))
		     '(make-noodles))

		  ((mss makes spaghetti)
		     '(make-spaghetti))

		  ((mss makes fettucini)
		     '(make-fettucini))

		  ((mss boils)
		     '(boil))

		  (t  
		     ;; No event type found, signal error
		     (return-from parse-sentence
			`(error "Can't parse ~A" ',s)))))

	    ;; determine agent role

	    (ml `(* (? agent) (+? ,@*verbs*) *) s)

	    (if (not (member agent '(nil user agent someone somebody)))
	       (setq agent-roles (list (list 'agent agent))))

	    ;; determine time role

	    (setq b- :-inf b+ :+inf e- :-inf e+ :+inf)
	    (cond 
	       ((ml '(* (+ starting from) before (?= b+) *) s))
	       ((ml '(* (+ starting from) after (?= b-) *) s))
	       ((ml '(* (+ starting from) (- at) (?= b-) (?= b+) *) s))
	       ((ml '(* (+ starting from) (- at) (?= b- b+) *) s))
	       (t (setq no-start-time t))
	       )

	    (cond 
	       ((ml '(* (+ ending to until) before (?= e+) *) s))
	       ((ml '(* (+ ending to until) after (?= e-) *) s))
	       ((ml '(* (+ ending to until) (- at) (?= e-) (?= e+) *) s))
	       ((ml '(* (+ ending to until) (- at) (?= e- e+) *) s))
	       (t (setq no-end-time t))
	       )

	    (if (and no-start-time no-end-time)
	       (then
		  (and (ml '(* before (?= e+) *) s)
		     (setq no-start-time nil))
		  (and (ml '(* after (?= b-) *) s)
		     (setq no-start-time nil))
		  (and (ml '(* at (?= b- b+ e- e+) *) s)
		     (setq no-start-time nil))
		  ))

	    (setq b+ (minimum b+ e+))
	    (setq e- (maximum e- b-))

	    (unless (and no-start-time no-end-time)
	       (setq time-roles `((time ,(make-time :b- b- :b+ b+ :e- e-
					 :e+ e+))))
	       )
	    
	    ;; build event description

	    (setq etype-and-descr (append 
					etype-and-descr
					agent-roles
					time-roles))

	    ;; determine whether it is an explain or update
	    ;; and construct command
	    (cond 
	       ((ml '(* explain *) s)
		  (if (not (ml '(let (- graph) (? graph) explain *)
			      s))
		     (setq graph (gentemp "EG")))
		  `(explain-observation ',etype-and-descr ',graph))
	       (t
		  `(update ',etype-and-descr)))
	    )
	 )
      ))




			 


      
