((:COHORT CLOSURE :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 5 :HEURISTIC-COMPONENT 0 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 11 :PLAN-ID |plan11385| :PLAN-COST
   5 :PLAN-KVAL 2 :PLAN-LENGTH 7 :UNSAT-COUNT 2 :FIRST-UNSAT
   (|op11383| (ISPEG $11381)) :NEXT-USER-PRECOND (|op11383| (ISPEG $11381)))
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1367 :MP-PRUNED 927))
 (:COHORT CLOSURE :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 10 :HEURISTIC-COMPONENT -5 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 23 :PLAN-ID |plan20241| :PLAN-COST
   10 :PLAN-KVAL 1 :PLAN-LENGTH 12 :UNSAT-COUNT 3 :FIRST-UNSAT
   (|op20238| (ISPEG $20236)) :NEXT-USER-PRECOND (|op20238| (ISPEG $20236)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 271 :NUM-GENERATED
   270 :MP-PRUNED 315)))
