((:COHORT PRIORITY :SOURCE-RANK 1 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 13 :HEURISTIC-COMPONENT -8 :BASE-GOAL-HEURISTIC 1
   :LEFT-WEDGE-ADJUSTMENT -9 :SOLUTION-DEPTH 42 :PLAN-ID |plan31225| :PLAN-COST
   13 :PLAN-KVAL 0 :PLAN-LENGTH 15 :UNSAT-COUNT 8 :FIRST-UNSAT
   (|op21073| (NOT ONS PEG2)) :NEXT-USER-PRECOND (|op21073| (NOT ONS PEG2)))
  :REPLAY
  (:RESULT NIL :SOLUTION EXPAND-LIMIT-EXCEEDED :SOLUTION-TYPE SYMBOL
   :SOLUTION-COST NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED
   1001 :NUM-GENERATED 1026 :MP-PRUNED 674))
 (:COHORT PRIORITY :SOURCE-RANK 2 :SOURCE
  (:PRIORITY 5 :SEARCH-COST 13 :HEURISTIC-COMPONENT -8 :BASE-GOAL-HEURISTIC 0
   :LEFT-WEDGE-ADJUSTMENT 0 :SOLUTION-DEPTH 40 :PLAN-ID |plan21069| :PLAN-COST
   13 :PLAN-KVAL 0 :PLAN-LENGTH 15 :UNSAT-COUNT 21 :FIRST-UNSAT
   (|op21064| (ISPEG $21063)) :NEXT-USER-PRECOND (|op21064| (ISPEG $21063)))
  :REPLAY
  (:RESULT NIL :SOLUTION OPEN-EXHAUSTED :SOLUTION-TYPE SYMBOL :SOLUTION-COST
   NIL :SOLUTION-KVAL NIL :SOLUTION-LENGTH NIL :NUM-EXPANDED 3 :NUM-GENERATED 2
   :MP-PRUNED 6)))
